version: '3'
services:
  redis:
    image: neo4j:5.2.0
    volumes:
      - neo4j-data:/data
    networks:
      - neo4j-net
    ports:
      - 10086:7474
      - 7687:7687
    environment:
      - NEO4J_AUTH=none
volumes:
  neo4j-data:
networks:
  neo4j-net:
